version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fast
    container_name: sanskrit-parser-backend
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - sanskrit-parser-data:/app/data
    networks:
      - traefik_net
      - sanskrit-network
    expose:
      - "8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    container_name: sanskrit-parser-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://sanskrit-parser.bondarenko-nikita.ru/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - traefik_net
      - sanskrit-network
    depends_on:
      - backend
    expose:
      - "3000"
    command: ["pnpm", "run", "dev"]

networks:
  sanskrit-network:
    driver: bridge
  traefik_net:
    external: true

volumes:
  sanskrit-parser-data: 